# Nmap 7.92 scan initiated Sat Jun 18 00:04:23 2022 as: nmap -p 22,80,5132,8433 -sC -sV -oA Depreciated/nmap/service-scan -Pn 192.168.66.170
Nmap scan report for 192.168.66.170
Host is up (0.053s latency).

PORT     STATE SERVICE VERSION
22/tcp   open  ssh     OpenSSH 8.2p1 Ubuntu 4ubuntu0.3 (Ubuntu Linux; protocol 2.0)
| ssh-hostkey: 
|   3072 c1:99:4b:95:22:25:ed:0f:85:20:d3:63:b4:48:bb:cf (RSA)
|   256 0f:44:8b:ad:ad:95:b8:22:6a:f0:36:ac:19:d0:0e:f3 (ECDSA)
|_  256 32:e1:2a:6c:cc:7c:e6:3e:23:f4:80:8d:33:ce:9b:3a (ED25519)
80/tcp   open  http    nginx 1.18.0 (Ubuntu)
|_http-title: Under Maintainence
|_http-server-header: nginx/1.18.0 (Ubuntu)
5132/tcp open  unknown
| fingerprint-strings: 
|   DNSStatusRequestTCP, DNSVersionBindReqTCP, NULL: 
|     Enter Username:
|   GenericLines, GetRequest, HTTPOptions, RTSPRequest: 
|     Enter Username: Enter OTP: Incorrect username or password
|   Help: 
|     Enter Username: Enter OTP:
|   RPCCheck: 
|     Enter Username: Traceback (most recent call last):
|     File "/opt/depreciated/messaging/messages.py", line 100, in <module>
|     main()
|     File "/opt/depreciated/messaging/messages.py", line 82, in main
|     username = input("Enter Username: ")
|     File "/usr/lib/python3.8/codecs.py", line 322, in decode
|     (result, consumed) = self._buffer_decode(data, self.errors, final)
|     UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
|   SSLSessionReq: 
|     Enter Username: Traceback (most recent call last):
|     File "/opt/depreciated/messaging/messages.py", line 100, in <module>
|     main()
|     File "/opt/depreciated/messaging/messages.py", line 82, in main
|     username = input("Enter Username: ")
|     File "/usr/lib/python3.8/codecs.py", line 322, in decode
|     (result, consumed) = self._buffer_decode(data, self.errors, final)
|     UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd7 in position 13: invalid continuation byte
|   TerminalServerCookie: 
|     Enter Username: Traceback (most recent call last):
|     File "/opt/depreciated/messaging/messages.py", line 100, in <module>
|     main()
|     File "/opt/depreciated/messaging/messages.py", line 82, in main
|     username = input("Enter Username: ")
|     File "/usr/lib/python3.8/codecs.py", line 322, in decode
|     (result, consumed) = self._buffer_decode(data, self.errors, final)
|_    UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe0 in position 5: invalid continuation byte
8433/tcp open  http    Werkzeug httpd 2.0.2 (Python 3.8.10)
|_http-title: Site doesn't have a title (text/html; charset=utf-8).
|_http-server-header: Werkzeug/2.0.2 Python/3.8.10
1 service unrecognized despite returning data. If you know the service/version, please submit the following fingerprint at https://nmap.org/cgi-bin/submit.cgi?new-service :
SF-Port5132-TCP:V=7.92%I=7%D=6/18%Time=62AD4ECE%P=x86_64-pc-linux-gnu%r(NU
SF:LL,10,"Enter\x20Username:\x20")%r(GenericLines,3A,"Enter\x20Username:\x
SF:20Enter\x20OTP:\x20Incorrect\x20username\x20or\x20password\n")%r(GetReq
SF:uest,3A,"Enter\x20Username:\x20Enter\x20OTP:\x20Incorrect\x20username\x
SF:20or\x20password\n")%r(HTTPOptions,3A,"Enter\x20Username:\x20Enter\x20O
SF:TP:\x20Incorrect\x20username\x20or\x20password\n")%r(RTSPRequest,3A,"En
SF:ter\x20Username:\x20Enter\x20OTP:\x20Incorrect\x20username\x20or\x20pas
SF:sword\n")%r(RPCCheck,1CD,"Enter\x20Username:\x20Traceback\x20\(most\x20
SF:recent\x20call\x20last\):\n\x20\x20File\x20\"/opt/depreciated/messaging
SF:/messages\.py\",\x20line\x20100,\x20in\x20<module>\n\x20\x20\x20\x20mai
SF:n\(\)\n\x20\x20File\x20\"/opt/depreciated/messaging/messages\.py\",\x20
SF:line\x2082,\x20in\x20main\n\x20\x20\x20\x20username\x20=\x20input\(\"En
SF:ter\x20Username:\x20\"\)\n\x20\x20File\x20\"/usr/lib/python3\.8/codecs\
SF:.py\",\x20line\x20322,\x20in\x20decode\n\x20\x20\x20\x20\(result,\x20co
SF:nsumed\)\x20=\x20self\._buffer_decode\(data,\x20self\.errors,\x20final\
SF:)\nUnicodeDecodeError:\x20'utf-8'\x20codec\x20can't\x20decode\x20byte\x
SF:200x80\x20in\x20position\x200:\x20invalid\x20start\x20byte\n")%r(DNSVer
SF:sionBindReqTCP,10,"Enter\x20Username:\x20")%r(DNSStatusRequestTCP,10,"E
SF:nter\x20Username:\x20")%r(Help,1B,"Enter\x20Username:\x20Enter\x20OTP:\
SF:x20")%r(SSLSessionReq,1D5,"Enter\x20Username:\x20Traceback\x20\(most\x2
SF:0recent\x20call\x20last\):\n\x20\x20File\x20\"/opt/depreciated/messagin
SF:g/messages\.py\",\x20line\x20100,\x20in\x20<module>\n\x20\x20\x20\x20ma
SF:in\(\)\n\x20\x20File\x20\"/opt/depreciated/messaging/messages\.py\",\x2
SF:0line\x2082,\x20in\x20main\n\x20\x20\x20\x20username\x20=\x20input\(\"E
SF:nter\x20Username:\x20\"\)\n\x20\x20File\x20\"/usr/lib/python3\.8/codecs
SF:\.py\",\x20line\x20322,\x20in\x20decode\n\x20\x20\x20\x20\(result,\x20c
SF:onsumed\)\x20=\x20self\._buffer_decode\(data,\x20self\.errors,\x20final
SF:\)\nUnicodeDecodeError:\x20'utf-8'\x20codec\x20can't\x20decode\x20byte\
SF:x200xd7\x20in\x20position\x2013:\x20invalid\x20continuation\x20byte\n")
SF:%r(TerminalServerCookie,1D4,"Enter\x20Username:\x20Traceback\x20\(most\
SF:x20recent\x20call\x20last\):\n\x20\x20File\x20\"/opt/depreciated/messag
SF:ing/messages\.py\",\x20line\x20100,\x20in\x20<module>\n\x20\x20\x20\x20
SF:main\(\)\n\x20\x20File\x20\"/opt/depreciated/messaging/messages\.py\",\
SF:x20line\x2082,\x20in\x20main\n\x20\x20\x20\x20username\x20=\x20input\(\
SF:"Enter\x20Username:\x20\"\)\n\x20\x20File\x20\"/usr/lib/python3\.8/code
SF:cs\.py\",\x20line\x20322,\x20in\x20decode\n\x20\x20\x20\x20\(result,\x2
SF:0consumed\)\x20=\x20self\._buffer_decode\(data,\x20self\.errors,\x20fin
SF:al\)\nUnicodeDecodeError:\x20'utf-8'\x20codec\x20can't\x20decode\x20byt
SF:e\x200xe0\x20in\x20position\x205:\x20invalid\x20continuation\x20byte\n"
SF:);
Service Info: OS: Linux; CPE: cpe:/o:linux:linux_kernel

Service detection performed. Please report any incorrect results at https://nmap.org/submit/ .
# Nmap done at Sat Jun 18 00:05:30 2022 -- 1 IP address (1 host up) scanned in 67.14 seconds
